// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeLrhy3GNo-p3MCkmq8fxj2VSwZUtpAoA',
    appId: '1:268202631484:web:24ae77f6ed599376f0be39',
    messagingSenderId: '268202631484',
    projectId: 'mi-actividad-2i6jx7',
    authDomain: 'mi-actividad-2i6jx7.firebaseapp.com',
    storageBucket: 'mi-actividad-2i6jx7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCobtGhSsvMiDy9q0TlA7ADwvOpVZi7j10',
    appId: '1:268202631484:android:8502644f6a927a48f0be39',
    messagingSenderId: '268202631484',
    projectId: 'mi-actividad-2i6jx7',
    storageBucket: 'mi-actividad-2i6jx7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTKpdv8ZjGx6I-oTewIaVYkPeG3h5dFmw',
    appId: '1:268202631484:ios:1be983b43c9dce33f0be39',
    messagingSenderId: '268202631484',
    projectId: 'mi-actividad-2i6jx7',
    storageBucket: 'mi-actividad-2i6jx7.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTKpdv8ZjGx6I-oTewIaVYkPeG3h5dFmw',
    appId: '1:268202631484:ios:1be983b43c9dce33f0be39',
    messagingSenderId: '268202631484',
    projectId: 'mi-actividad-2i6jx7',
    storageBucket: 'mi-actividad-2i6jx7.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeLrhy3GNo-p3MCkmq8fxj2VSwZUtpAoA',
    appId: '1:268202631484:web:8813fe49658679bdf0be39',
    messagingSenderId: '268202631484',
    projectId: 'mi-actividad-2i6jx7',
    authDomain: 'mi-actividad-2i6jx7.firebaseapp.com',
    storageBucket: 'mi-actividad-2i6jx7.firebasestorage.app',
  );
}
